### ISSUE TITLE
[Question] Use custom web components in TEI Publisher

### ISSUE THREAD

**Issue by nakamura196** [eeditiones/pb-extension-template#3]
Hi,

I created a pb-clipboard example, and built a tei-publisher-app based on the documentation.
And, I tried to use the component in the letter.html template, but it doesn't work.

![スクリーンショット 2020-09-29 9 47 19](https://user-images.githubusercontent.com/5351691/94499954-f3677580-0238-11eb-8ff8-b9a675ef6714.png)

Do I need to load a script "pb-extension-bundle.js" like "pb-components-bundle.js"?

`<script type="module" src="pb-components-bundle.js" data-template="pages:load-components"/>`

But, of cource, a following file does not exist, so how should I load any related scripts?

https://unpkg.com/@teipublisher/pb-components@1.3.0/dist/pb-extension-bundle.js

By the way, I updated the version of the tei-publisher-app to "6.0.3", so I think the app was built successfully. 
If needed, I would like to send the xar file to you.

![スクリーンショット 2020-09-29 10 03 38](https://user-images.githubusercontent.com/5351691/94500769-18f57e80-023b-11eb-972b-48c4b25d9973.png)

regards

**Comment by wolfgangmm** [comment]
Yes, you would need to load `pb-extension-bundle.js` after `pb-components-bundle.js` on every HTML page on which you would like to use the component.

```html
<script type="module" src="resources/scripts/pb-extension-bundle.js"></script>
```

I also noticed the [README](https://github.com/eeditiones/pb-extension-template/blob/master/README.md) was missing some steps. I have revised it and made sure the current description actually works. Please have a look there.

**Comment by nakamura196** [comment]
![スクリーンショット 2020-09-30 8 58 16](https://user-images.githubusercontent.com/5351691/94628528-31c56900-02fb-11eb-8d99-809b992684b0.png)

It works! Thank you for your help.
I will try to learn more about tei-publisher.

And I would like to share 2 things.

1. Besides the way you instructed, I also loaded `pb-extension-bundle.js` with a following way.

```html
<script type="module" src="pb-extension-bundle.js" data-template="pages:load-components"/>
```

2. `ant xar-local` did not work on my environments.

Error message:
`/Users/XXX/git/d_pb/tei-publisher-app/build.xml:77: Execute failed: java.io.IOException: Cannot run program "/usr/local/bin/npm" (in directory "/Users/XXX/git/d_pb/tei-publisher-app"): error=2, No such file or directory`

 I use `/Users/XXX/.nodebrew/current/bin/npm`, so I conducted `npm install` and `ant prepare`, `ant xar` indivisualy.

I hope my story is useful for you.

regards
